//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueVends.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int OrderQuantity { get; set; }
        public System.Guid UserID { get; set; }
        public System.Guid VariantID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Variant Variant { get; set; }
    }
}
