//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueVends.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrderJunction
    {
        public int SellingPrice { get; set; }
        public string Variant { get; set; }
        public System.Guid OrderID { get; set; }
        public System.Guid ProductID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
