//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueVends.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductImage = new HashSet<ProductImage>();
            this.ProductOrderJunction = new HashSet<ProductOrderJunction>();
            this.Variant = new HashSet<Variant>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public int Discount { get; set; }
        public int ListingPrice { get; set; }
        public int Inventory { get; set; }
        public int QuantitySold { get; set; }
        public int OrderLimit { get; set; }
        public string ImageURL { get; set; }
        public System.Guid CategoryID { get; set; }
        public string Description { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImage> ProductImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOrderJunction> ProductOrderJunction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Variant> Variant { get; set; }
    }
}
